name: task_manager_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  pin_code_fields: ^8.0.1
  device_preview: ^1.2.0
  flutter_native_splash: ^2.4.7
  icons_launcher: ^3.0.3
  launcher_name: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


icons_launcher:
  image_path: "assets/images/icon_launcher_logo.png"
  adaptive_background_color: "#ffffff"
  adaptive_foreground_image: "assets/images/icon_launcher_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  android: true
  ios: true
  web: false
  color_dark: "#000000"
  background_image: "assets/images/background.png"
  image: "assets/images/logo.png"
  branding: "assets/images/meer's_brand_img.png"

  android_12:
    color: "#ffffff"
    color_dark: "#000000"
    image: "assets/images/logo.png"
    branding: "assets/images/meer's_brand_img.png"


launcher_name:
  default: "Task Manager"